/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/components/Footer': RouteRecordInfo<'/admin/components/Footer', '/admin/components/Footer', Record<never, never>, Record<never, never>>,
    '/admin/components/Header': RouteRecordInfo<'/admin/components/Header', '/admin/components/Header', Record<never, never>, Record<never, never>>,
    '/admin/layouts/default': RouteRecordInfo<'/admin/layouts/default', '/admin/layouts/default', Record<never, never>, Record<never, never>>,
    '/admin/pages/': RouteRecordInfo<'/admin/pages/', '/admin/pages', Record<never, never>, Record<never, never>>,
    '/admin/pages/product/': RouteRecordInfo<'/admin/pages/product/', '/admin/pages/product', Record<never, never>, Record<never, never>>,
    '/admin/pages/product/create/': RouteRecordInfo<'/admin/pages/product/create/', '/admin/pages/product/create', Record<never, never>, Record<never, never>>,
    '/admin/pages/product/edit/': RouteRecordInfo<'/admin/pages/product/edit/', '/admin/pages/product/edit', Record<never, never>, Record<never, never>>,
    '/admin/pages/projectss/': RouteRecordInfo<'/admin/pages/projectss/', '/admin/pages/projectss', Record<never, never>, Record<never, never>>,
    '/admin/pages/projectss/create/': RouteRecordInfo<'/admin/pages/projectss/create/', '/admin/pages/projectss/create', Record<never, never>, Record<never, never>>,
    '/admin/pages/projectss/edit/': RouteRecordInfo<'/admin/pages/projectss/edit/', '/admin/pages/projectss/edit', Record<never, never>, Record<never, never>>,
    '/frontend/components/Footer': RouteRecordInfo<'/frontend/components/Footer', '/frontend/components/Footer', Record<never, never>, Record<never, never>>,
    '/frontend/components/Header': RouteRecordInfo<'/frontend/components/Header', '/frontend/components/Header', Record<never, never>, Record<never, never>>,
    '/frontend/layouts/default': RouteRecordInfo<'/frontend/layouts/default', '/frontend/layouts/default', Record<never, never>, Record<never, never>>,
    '/frontend/pages/': RouteRecordInfo<'/frontend/pages/', '/frontend/pages', Record<never, never>, Record<never, never>>,
  }
}
